const ContainerStatement = require('../../../models/ContainerStatement');
const Sales = require('../../../models/Sales');
const { heading, money, limitedList } = require('../formatter');
const { escapeRegex, sum } = require('./helpers');

const readOnlyContainerSummary = async (containerNo) => {
  const sales = await Sales.find({
    containerNo: { $regex: `^${escapeRegex(containerNo)}$`, $options: 'i' }
  }).sort({ createdAt: 1 }).lean();
  const stored = await ContainerStatement.findOne({
    containerNo: { $regex: `^${escapeRegex(containerNo)}$`, $options: 'i' }
  }).lean();
  if (!sales.length && !stored) return null;

  const products = sales.length
    ? sales.map((sale) => ({
      product: sale.product,
      quantity: sale.quantity,
      amount: (Number(sale.quantity) * Number(sale.rate))
        * (1 + Number(sale.vatPercentage || 0) / 100)
    }))
    : stored.products;
  const expenses = (stored?.expenses || []).filter((expense) => !expense.isAutoGenerated);
  const grossSale = sum(products, 'amount');
  const totalExpenses = sum(expenses, 'amount');

  return {
    containerNo: stored?.containerNo || sales[0]?.containerNo || containerNo,
    products,
    expenses,
    grossSale,
    totalExpenses,
    netSale: grossSale - totalExpenses,
    totalQuantity: sum(products, 'quantity')
  };
};

const handleContainerStatements = async ({ entities, intent }) => {
  if (intent === 'container.list') {
    const total = await ContainerStatement.countDocuments();
    const rows = await ContainerStatement.find().sort({ createdAt: -1 }).limit(entities.limit).lean();
    return `${heading('Container statements')}\n${limitedList(rows, (statement) => (
      `• *${statement.containerNo}* — Net ${money(statement.netSale)}\n` +
      `  Gross ${money(statement.grossSale)} | Expenses ${money(statement.totalExpenses)}`
    ), total, entities.limit)}`;
  }

  const summary = await readOnlyContainerSummary(entities.containerNo);
  if (!summary) return `No statement or sales were found for container *${entities.containerNo}*.`;
  return [
    heading(`Container — ${summary.containerNo}`),
    `Products: ${summary.products.length}`,
    `Quantity: ${summary.totalQuantity}`,
    `Gross sales: ${money(summary.grossSale)}`,
    `Expenses: ${money(summary.totalExpenses)}`,
    `Net sales: ${money(summary.netSale)}`,
    '',
    heading('Products'),
    limitedList(summary.products, (product) => (
      `• ${product.product} — ${product.quantity} units | ${money(product.amount)}`
    ))
  ].join('\n');
};

module.exports = { handleContainerStatements };
