const ContainerStatement = require('../models/ContainerStatement');
const Sales = require('../models/Sales');
const PDFGenerator = require('../utils/pdfGenerator');
const { ceilToTwoDecimals } = require('../utils/numberFormatter');

const buildStatementDataFromSales = (salesData = []) => {
  const products = salesData.map((sale, index) => {
    const quantity = Number(sale.quantity) || 0;
    const totalAmount = ceilToTwoDecimals(sale.amount || 0);
    const unitPrice = quantity > 0 ? ceilToTwoDecimals(totalAmount / quantity) : ceilToTwoDecimals(sale.rate || 0);

    return {
      srNo: index + 1,
      product: sale.product,
      quantity,
      unitPrice,
      amount: totalAmount,
    };
  });

  return { products };
};

const syncStatementWithSalesData = (statement, { products }, userId) => {
  statement.products = products;
  if (userId) {
    statement.updatedBy = userId;
  }
  statement.markModified('products');

  if (!Array.isArray(statement.expenses)) {
    statement.expenses = [];
    statement.markModified('expenses');
  }

  const filteredExpenses = statement.expenses.filter((expense) => !expense.isAutoGenerated);
  if (filteredExpenses.length !== statement.expenses.length) {
    statement.expenses = filteredExpenses;
    statement.markModified('expenses');
  }
};

const hydrateStatementForContainer = async (containerNo, userId) => {
  const salesData = await Sales.find({ containerNo }).populate('createdBy', 'name email').sort({ createdAt: 1 });
  if (!salesData.length) {
    return null;
  }

  let statement = await ContainerStatement.getByContainerNo(containerNo);
  if (!statement) {
    statement = new ContainerStatement({
      containerNo,
      products: [],
      expenses: [],
      createdBy: userId,
    });
  }

  const statementData = buildStatementDataFromSales(salesData);
  syncStatementWithSalesData(statement, statementData, userId);
  await statement.save();

  return { statement, salesData, statementData };
};

// @desc    Get container statement by container number
// @route   GET /api/container-statements/:containerNo
// @access  Private
const getContainerStatement = async (req, res) => {
  try {
    const { containerNo } = req.params;

    if (!containerNo) {
      return res.status(400).json({
        success: false,
        error: 'Container number is required',
        message: 'Please provide a valid container number'
      });
    }

    const hydrated = await hydrateStatementForContainer(containerNo, req.user?.id);
    if (!hydrated) {
      return res.status(404).json({
        success: false,
        error: 'Container not found',
        message: `No data found for container number: ${containerNo}`
      });
    }

    res.json({
      success: true,
      data: hydrated.statement,
      message: 'Container statement retrieved successfully'
    });

  } catch (error) {
    console.error('Get container statement error:', error);
    res.status(500).json({
      success: false,
      error: 'Server error',
      message: 'Internal server error'
    });
  }
};

// @desc    Create or update container statement
// @route   POST /api/container-statements
// @access  Private
const createContainerStatement = async (req, res) => {
  try {
    const { containerNo, products, expenses } = req.body;

    if (!containerNo) {
      return res.status(400).json({
        success: false,
        error: 'Container number is required',
        message: 'Please provide a valid container number'
      });
    }

    // Check if statement already exists
    const existingStatement = await ContainerStatement.getByContainerNo(containerNo);

    if (existingStatement) {
      return res.status(400).json({
        success: false,
        error: 'Statement already exists',
        message: `Container statement for ${containerNo} already exists. Use update endpoint instead.`
      });
    }

    const statement = new ContainerStatement({
      containerNo,
      products: products || [],
      expenses: expenses || [],
      createdBy: req.user.id
    });

    await statement.save();

    res.status(201).json({
      success: true,
      data: statement,
      message: 'Container statement created successfully'
    });

  } catch (error) {
    console.error('Create container statement error:', error);
    res.status(500).json({
      success: false,
      error: 'Server error',
      message: 'Internal server error'
    });
  }
};

// @desc    Update container statement
// @route   PUT /api/container-statements/:id
// @access  Private
const updateContainerStatement = async (req, res) => {
  try {
    const { id } = req.params;
    const { products, expenses } = req.body;

    const statement = await ContainerStatement.findById(id);

    if (!statement) {
      return res.status(404).json({
        success: false,
        error: 'Statement not found',
        message: 'Container statement not found'
      });
    }

    // Update fields
    if (products) statement.products = products;
    if (expenses) statement.expenses = expenses;
    statement.updatedBy = req.user.id;

    await statement.save();

    res.json({
      success: true,
      data: statement,
      message: 'Container statement updated successfully'
    });

  } catch (error) {
    console.error('Update container statement error:', error);
    res.status(500).json({
      success: false,
      error: 'Server error',
      message: 'Internal server error'
    });
  }
};

// @desc    Add expense to container statement
// @route   POST /api/container-statements/:id/expenses
// @access  Private
const addExpense = async (req, res) => {
  try {
    const { id } = req.params;
    const { description, amount } = req.body;

    if (!description || amount === undefined || amount === null) {
      return res.status(400).json({
        success: false,
        error: 'Missing required fields',
        message: 'Description and amount are required'
      });
    }

    const parsedAmount = Number(amount);
    if (Number.isNaN(parsedAmount) || parsedAmount <= 0) {
      return res.status(400).json({
        success: false,
        error: 'Invalid amount',
        message: 'Please provide a valid amount greater than zero'
      });
    }

    const statement = await ContainerStatement.findById(id);

    if (!statement) {
      return res.status(404).json({
        success: false,
        error: 'Statement not found',
        message: 'Container statement not found'
      });
    }

    if (!Array.isArray(statement.expenses)) {
      statement.expenses = [];
    }

    statement.expenses.push({
      description: description.trim(),
      amount: ceilToTwoDecimals(parsedAmount),
      isAutoGenerated: false,
    });
    statement.markModified('expenses');
    statement.updatedBy = req.user.id;
    await statement.save();

    res.json({
      success: true,
      data: statement,
      message: 'Expense added successfully'
    });

  } catch (error) {
    console.error('Add expense error:', error);
    res.status(500).json({
      success: false,
      error: 'Server error',
      message: 'Internal server error'
    });
  }
};

// @desc    Remove expense from container statement
// @route   DELETE /api/container-statements/:id/expenses/:expenseId
// @access  Private
const removeExpense = async (req, res) => {
  try {
    const { id, expenseId } = req.params;

    const statement = await ContainerStatement.findById(id);

    if (!statement) {
      return res.status(404).json({
        success: false,
        error: 'Statement not found',
        message: 'Container statement not found'
      });
    }

    const expense = statement.expenses.id(expenseId);
    if (!expense) {
      return res.status(404).json({
        success: false,
        error: 'Expense not found',
        message: 'Expense entry not found'
      });
    }

    if (expense.isAutoGenerated) {
      return res.status(400).json({
        success: false,
        error: 'Protected expense',
        message: 'Auto-calculated VAT expense cannot be removed'
      });
    }

    expense.remove();
    statement.markModified('expenses');
    statement.updatedBy = req.user.id;
    await statement.save();

    res.json({
      success: true,
      data: statement,
      message: 'Expense removed successfully'
    });

  } catch (error) {
    console.error('Remove expense error:', error);
    res.status(500).json({
      success: false,
      error: 'Server error',
      message: 'Internal server error'
    });
  }
};

// @desc    Get all container statements
// @route   GET /api/container-statements
// @access  Private
const getAllContainerStatements = async (req, res) => {
  try {
    const { page = 1, limit = 10, search = '' } = req.query;

    const statements = await ContainerStatement.getAllStatements(
      parseInt(page),
      parseInt(limit),
      search
    );

    const total = await ContainerStatement.countDocuments(
      search ? { containerNo: { $regex: search, $options: 'i' } } : {}
    );

    res.json({
      success: true,
      data: statements,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total,
        totalPages: Math.ceil(total / parseInt(limit))
      },
      message: 'Container statements retrieved successfully'
    });

  } catch (error) {
    console.error('Get all container statements error:', error);
    res.status(500).json({
      success: false,
      error: 'Server error',
      message: 'Internal server error'
    });
  }
};

// @desc    Delete container statement
// @route   DELETE /api/container-statements/:id
// @access  Private (Admin only)
const deleteContainerStatement = async (req, res) => {
  try {
    const { id } = req.params;

    const statement = await ContainerStatement.findById(id);

    if (!statement) {
      return res.status(404).json({
        success: false,
        error: 'Statement not found',
        message: 'Container statement not found'
      });
    }

    await ContainerStatement.findByIdAndDelete(id);

    res.json({
      success: true,
      message: 'Container statement deleted successfully'
    });

  } catch (error) {
    console.error('Delete container statement error:', error);
    res.status(500).json({
      success: false,
      error: 'Server error',
      message: 'Internal server error'
    });
  }
};

module.exports = {
  getContainerStatement,
  createContainerStatement,
  updateContainerStatement,
  addExpense,
  removeExpense,
  getAllContainerStatements,
  deleteContainerStatement,
  downloadStatementPDF: async (req, res) => {
    try {
      const { containerNo } = req.params;
      if (!containerNo) {
        return res.status(400).json({ success: false, message: 'Container number is required' });
      }

      const hydrated = await hydrateStatementForContainer(containerNo, req.user?.id);
      if (!hydrated) {
        return res.status(404).json({ success: false, message: `No data found for ${containerNo}` });
      }

      const { statement, salesData } = hydrated;
      const pdf = new PDFGenerator();
      const companyName = salesData[0]
        ? (salesData[0].supplier || salesData[0].customer || '')
        : '';
      const uniqueMarkas = Array.from(new Set(salesData.map((s) => s.marka).filter(Boolean)));
      const srNo = uniqueMarkas.length > 0 ? uniqueMarkas[0] : '';
      pdf.generateContainerStatement(res, statement, { companyName, srNo });
    } catch (error) {
      console.error('Download statement PDF error:', error);
      res.status(500).json({ success: false, message: 'Failed to generate PDF' });
    }
  }
};
